# Generated by Django 4.2.4 on 2023-09-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='phone_number',
            field=models.CharField(default=None, max_length=10, unique=True),
        ),
    ]
